### ISSUE TITLE
New secrets loading module: Empty `files` key causes surprising error

### ISSUE THREAD

**Issue by mhjacks** [hybrid-cloud-patterns/common#184]
Under the current module, when the files: key is defined in values_secret.yaml but has no entries, it throws the error that NoneType is not iterable when validating the file paths.

This potentially surprising to the user - maybe there should be a validation that files: points to a dict type?

**Comment by day0hero** [comment]
here is the complete errror:
```An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/jrickard/.ansible/tmp/ansible-tmp-1664994985.2909513-413311-242601022481252/AnsiballZ_vault_load_secrets.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/jrickard/.ansible/tmp/ansible-tmp-1664994985.2909513-413311-242601022481252/AnsiballZ_vault_load_secrets.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/jrickard/.ansible/tmp/ansible-tmp-1664994985.2909513-413311-242601022481252/AnsiballZ_vault_load_secrets.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.vault_load_secrets', init_globals=dict(_module_fqn='ansible.modules.vault_load_secrets', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vault_load_secrets_payload_7srbr3th/ansible_vault_load_secrets_payload.zip/ansible/modules/vault_load_secrets.py\", line 371, in <module>\n  File \"/tmp/ansible_vault_load_secrets_payload_7srbr3th/ansible_vault_load_secrets_payload.zip/ansible/modules/vault_load_secrets.py\", line 367, in main\n  File \"/tmp/ansible_vault_load_secrets_payload_7srbr3th/ansible_vault_load_secrets_payload.zip/ansible/modules/vault_load_secrets.py\", line 353, in run\n  File \"/tmp/ansible_vault_load_secrets_payload_7srbr3th/ansible_vault_load_secrets_payload.zip/ansible/modules/vault_load_secrets.py\", line 206, in sanitize_values\nTypeError: 'NoneType' object is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

values-secret.yaml used:
```
---
secrets:
  # NEVER COMMIT THESE VALUES TO GIT
  config-demo:
    # Secret used for demonstrating vault storage, external secrets, and ACM distribution
    secret: VALUSE

  # Required for automated spoke deployment
  aws:
      access_key_id: VALUE
      secret_access_key: VALUE

# Required for automated spoke deployment
files:
  # # ssh-rsa AAA...
  # publickey: ~/.ssh/id_rsa.pub
  #
  # # -----BEGIN RSA PRIVATE KEY
  # # ...
  # # -----END RSA PRIVATE KEY
  # privatekey: ~/.ssh/id_rsa
  #
  # # {"auths":{"cloud.openshift.com":{"auth":"b3Blb... }}}
  # openshiftPullSecret: ~/.dockerconfigjson
  #
  # azureOsServicePrincipal: ~/osServicePrincipal.json
```
